export const RECEIVE_ADDRESS='RECEIVE_ADDRESS';
export const RECEIVE_CATEGORYS='RECEIVE_CATEGORYS';
export const RECEIVE_SHOPS='RECEIVE_SHOPS';
export const RECEIVE_USER_INFO='RECEIVE_USER_INFO';
export const RECEIVE_SHOP_INFO='RECEIVE_SHOP_INFO';
export const RECEIVE_SHOP_RATINGS='RECEIVE_SHOP_RATINGS';
export const RECEIVE_SHOP_GOODS='RECEIVE_SHOP_GOODS';

export const INCREMENT_COUNT='INCREMENT_COUNT';
export const DEINCREMENT_COUNT='DEINCREMENT_COUNT';
export const CLEARCART='CLEARCART';
